_target_: lid.callbacks.monitor_lid_curve.MonitorLIDCurve
device: # the device that FLIPD estimator uses for JVP computation
  _target_: torch.device
  type: cuda
dataset: ${dataset.training_torch_data}
# The sweeping arguments
sweeping_arg: t
sweeping_range:
  _target_: numpy.linspace
  start: 0.0
  stop: 1.0
  num: 50
# the model directory
use_artifact: false
lid_estimator_partial:
  _target_: lid.diffusions.FlipdEstimator
  _partial_: true
  ambient_dim: ${dataset.data_dim}

frequency: 1
subsample_size: 128
verbose: True
save_image: ${dataset.is_image}
batch_size: 128

lid_estimation_args:
  verbose: True # set to False
  chunk_size: 512
  seed: 42
  method: deterministic
  hutchinson_sample_count: 50
