_target_: metrics.mem.detectors.ConditionalUnconditionalLIDRatio
sde: ${dgm.architecture}
lid_estimator_partial:
  _target_: lid.diffusions.FlipdEstimator
  _partial_: true
  device: ${device}
t: 0.01
hutchinson_sample_count: 1
